title: "CS105 – Introduction to Computing Concepts"
description: "Course site for UMass Boston CS105"

# Use Just the Docs theme
remote_theme: just-the-docs/just-the-docs@v0.6.2
plugins:
  - jekyll-remote-theme

# URLs
url: "https://kinali.github.io"
baseurl: "/CS105"   # Must match your repo name exactly (case sensitive)

# Dark mode
color_scheme: dark

# Optional custom CSS (you can add later if you want pure black)
# just_the_docs:
#   custom_css:
#     - assets/css/custom.css

